---
title: 'MITx: 24.118x Paradox and Infinity'
output:
  html_document:
    keep_md: yes
    theme: readable
  pdf_document: default
---

## Disclaimer

This is a compilation of the MIT's massive open online course (MOOC) pertaining to the study of philosophy. In anticipation of the course material being removed in the near future, I will carefully compile the material into a document verbatim so enthusiasts can have access to what seems to be a course filled with wonderful endless knowledge. Therefore, I, Eddo Williams Hintoso, do not claim any ownership to the material presented. For reference, [here](https://www.edx.org/course/paradox-infinity-mitx-24-118x#!) is the original URL link to the original edX class, which ran from June to August of 2015. There is also an alternative form of the class published on MIT Open Courseware (OCW), provided [here](http://ocw.mit.edu/courses/linguistics-and-philosophy/24-118-paradox-infinity-spring-2013/).

## About the Course

In *Paradox and Infinity* we will study a cluster of puzzles, paradoxes and intellectual wonders, and discuss their philosophical implications.

The class is divided into three modules:

- **Time Travel and Free Will**: Learn about whether time travel is logically possible, and whether it is compatible with free will.
- **Infinity**: Learn about how some infinities are bigger than others, and explore the mind-boggling hierarchy of bigger and bigger infinities.
- **Computability and Gödel’s Theorem**: Learn about how some mathematical functions are so complex, that no computer could possibly compute them. Use this result to prove Gödel’s famous Incompleteness Theorem.

### Prerequisites

No prerequisites, but experience in college-level mathematics or computer-science could be helpful.